### ISSUE TITLE
Roadmap is out of date

### ISSUE THREAD

**Issue by jimmckeeth** [spacedriveapp/spacedrive#2808]
### Check for other issues

- [X] I've checked for other issues, and none exist.

### Are you on the latest version?

- [X] I'm on the latest version of the app or website.

### Where did you find this mistake?

- [ ] Desktop app
- [ ] Mobile app
- [ ] Documentation
- [X] Website (spacedrive.com)
- [ ] Other (please specify)

### Other location

https://www.spacedrive.com/roadmap

### Description

The roadmap was last updated on March 13, 2024 for version 0.2 Alpha

It makes it hard to know what features are implemented and which are not.

![image](https://github.com/user-attachments/assets/a748cbc5-cdae-4f31-a5d3-20e3082a61be)

![image](https://github.com/user-attachments/assets/31cf52f4-bea7-4114-a499-0d69500e540b)

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by menelic** [comment]
It would be realy great if the roadmap could be updated. I am trying to convince my team to use spacedrive, but this outdated roadmap leads to confusion and questoins

**Comment by jamiepine** [comment]
Closing due to v2 rewrite. If you encounter this issue in v2, please open a new issue.

**Comment by jimmckeeth** [comment]
@jamiepine 
so is the existing v1 roadmap and blog just going to remain out of date? Having those abandoned pages as the default doesn't help the product look active.

https://www.spacedrive.com/roadmap
https://www.spacedrive.com/blog

**Comment by jamiepine** [comment]
Of course I don't plan on leaving that there, I have a whole new landing page, blog and roadmap nearly ready to go live. I am working towards this asap, but it's a process. When it does go live it will drive traffic to v2 download which needs to be stable first, hence the transition period we're in rn.

**Comment by jimmckeeth** [comment]
Ok, makes sense. Congratulations on the rewrite!
